# This is a basic workflow to help you get started with Actions
name: test-actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #- name: Dispaly branch
    #  run: git branch
    
    #- name: Display github_ref
    #  run: echo ${{ github.ref }}
      
    #- name: Setup Nuget.exe
    #  uses: warrenbuckley/Setup-Nuget@v1
    
    #- name: Restore NuGet Packages
    #  run: nuget restore OpenTracingProj.sln   
    
    #- name: setup-msbuild
    #  uses: microsoft/setup-msbuild@v1
      
    #- name: Build and Publish Project
    #  run: msbuild OpenTracingProj.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Mkdir and Copy files
      run: |
       mkdir Artifacts
       copy-item -path OpenTracingProj/Database/proscheduler.dacpac -destination Artifacts
       copy-item -path OpenTracingProj/UpdateScript.sql -destination Artifacts

    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:        
        name: ProjectFiles        
        path: Artifacts/
    
  build2:
    needs: build
    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2   
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with: 
        name: ProjectFiles        
        path: OpenTracingProj/Download
          
    - name: Display folder
      run: dir OpenTracingProj/Download
    
    
      
