# This is a basic workflow to help you get started with Actions
name: test-actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [github-actions]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:    
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it    
    - uses: actions/checkout@v2      
        
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
        
    - name: msbuild version
      run: msbuild -version
      
    - name: GITHUB_WORKSPACE
      run: echo $Env:GITHUB_WORKSPACE
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Restore NuGet Packages
      run: nuget restore OpenTracingProj.sln
    
    - name: Build and Publish Project
      run: msbuild OpenTracingProj.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
          
    - name: Display content directory
      run: dir 
    
    #- name: Upload artifact
    #  uses: actions/upload-artifact@v1.0.0
    #  with:        
    #    name: published_app        
    #    path: OpenTracingProj\bin\Release
